apiVersion: v1
kind: Secret
metadata:
  name: hello-secret-{{ .Release.Name }}  # Nombre único por release
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
data:
  secretValue: {{ .Values.config.secretValue | b64enc | quote }}
